"""User

Revision ID: c4b20f31cb25
Revises: 90b0f6a23c8e
Create Date: 2024-07-18 10:40:48.419758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b20f31cb25'
down_revision: Union[str, None] = '90b0f6a23c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.Text(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
